# Generated by Django 2.1.7 on 2019-03-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ad_text',
            field=models.CharField(max_length=900),
        ),
    ]
