# Generated by Django 2.1.7 on 2019-03-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190328_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ad_text',
            field=models.CharField(max_length=855),
        ),
    ]
